# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master-comm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11master-comm.proto\x12\x06stream\"\x17\n\x15GetListOfNodesRequest\")\n\x16GetListOfNodesResponse\x12\x0f\n\x07nodeips\x18\x01 \x03(\t\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\'\n\x15NodeDownUpdateRequest\x12\x0e\n\x06nodeip\x18\x01 \x01(\t\"(\n\x16NodeDownUpdateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xb3\x01\n\x0bReplication\x12Q\n\x0eNodeDownUpdate\x12\x1d.stream.NodeDownUpdateRequest\x1a\x1e.stream.NodeDownUpdateResponse\"\x00\x12Q\n\x0eGetListOfNodes\x12\x1d.stream.GetListOfNodesRequest\x1a\x1e.stream.GetListOfNodesResponse\"\x00\x42\x15\n\x11org.master.protosP\x01\x62\x06proto3')



_GETLISTOFNODESREQUEST = DESCRIPTOR.message_types_by_name['GetListOfNodesRequest']
_GETLISTOFNODESRESPONSE = DESCRIPTOR.message_types_by_name['GetListOfNodesResponse']
_STATUSRESPONSE = DESCRIPTOR.message_types_by_name['StatusResponse']
_NODEDOWNUPDATEREQUEST = DESCRIPTOR.message_types_by_name['NodeDownUpdateRequest']
_NODEDOWNUPDATERESPONSE = DESCRIPTOR.message_types_by_name['NodeDownUpdateResponse']
GetListOfNodesRequest = _reflection.GeneratedProtocolMessageType('GetListOfNodesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETLISTOFNODESREQUEST,
  '__module__' : 'master_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.GetListOfNodesRequest)
  })
_sym_db.RegisterMessage(GetListOfNodesRequest)

GetListOfNodesResponse = _reflection.GeneratedProtocolMessageType('GetListOfNodesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETLISTOFNODESRESPONSE,
  '__module__' : 'master_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.GetListOfNodesResponse)
  })
_sym_db.RegisterMessage(GetListOfNodesResponse)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'master_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)

NodeDownUpdateRequest = _reflection.GeneratedProtocolMessageType('NodeDownUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _NODEDOWNUPDATEREQUEST,
  '__module__' : 'master_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.NodeDownUpdateRequest)
  })
_sym_db.RegisterMessage(NodeDownUpdateRequest)

NodeDownUpdateResponse = _reflection.GeneratedProtocolMessageType('NodeDownUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _NODEDOWNUPDATERESPONSE,
  '__module__' : 'master_comm_pb2'
  # @@protoc_insertion_point(class_scope:stream.NodeDownUpdateResponse)
  })
_sym_db.RegisterMessage(NodeDownUpdateResponse)

_REPLICATION = DESCRIPTOR.services_by_name['Replication']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021org.master.protosP\001'
  _GETLISTOFNODESREQUEST._serialized_start=29
  _GETLISTOFNODESREQUEST._serialized_end=52
  _GETLISTOFNODESRESPONSE._serialized_start=54
  _GETLISTOFNODESRESPONSE._serialized_end=95
  _STATUSRESPONSE._serialized_start=97
  _STATUSRESPONSE._serialized_end=129
  _NODEDOWNUPDATEREQUEST._serialized_start=131
  _NODEDOWNUPDATEREQUEST._serialized_end=170
  _NODEDOWNUPDATERESPONSE._serialized_start=172
  _NODEDOWNUPDATERESPONSE._serialized_end=212
  _REPLICATION._serialized_start=215
  _REPLICATION._serialized_end=394
# @@protoc_insertion_point(module_scope)
