# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import master_comm_pb2 as master__comm__pb2


class ReplicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NodeDownUpdate = channel.unary_unary(
                '/stream.Replication/NodeDownUpdate',
                request_serializer=master__comm__pb2.NodeDownUpdateRequest.SerializeToString,
                response_deserializer=master__comm__pb2.NodeDownUpdateResponse.FromString,
                )
        self.GetListOfNodes = channel.unary_unary(
                '/stream.Replication/GetListOfNodes',
                request_serializer=master__comm__pb2.GetListOfNodesRequest.SerializeToString,
                response_deserializer=master__comm__pb2.GetListOfNodesResponse.FromString,
                )


class ReplicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NodeDownUpdate(self, request, context):
        """Methods required for Sentinel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetListOfNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NodeDownUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeDownUpdate,
                    request_deserializer=master__comm__pb2.NodeDownUpdateRequest.FromString,
                    response_serializer=master__comm__pb2.NodeDownUpdateResponse.SerializeToString,
            ),
            'GetListOfNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetListOfNodes,
                    request_deserializer=master__comm__pb2.GetListOfNodesRequest.FromString,
                    response_serializer=master__comm__pb2.GetListOfNodesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stream.Replication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Replication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NodeDownUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stream.Replication/NodeDownUpdate',
            master__comm__pb2.NodeDownUpdateRequest.SerializeToString,
            master__comm__pb2.NodeDownUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetListOfNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stream.Replication/GetListOfNodes',
            master__comm__pb2.GetListOfNodesRequest.SerializeToString,
            master__comm__pb2.GetListOfNodesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
