# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\x12\x07stream1\"9\n\x14proposeLeaderRequest\x12\x11\n\tprocessId\x18\x01 \x01(\x03\x12\x0e\n\x06nodeip\x18\x02 \x01(\t\"\'\n\x15proposeLeaderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\'\n\x13updateLeaderRequest\x12\x10\n\x08leaderip\x18\x01 \x01(\t\"&\n\x14updateLeaderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\")\n\x15GetListOfNodesRequest\x12\x10\n\x08workerip\x18\x01 \x01(\t\")\n\x16GetListOfNodesResponse\x12\x0f\n\x07nodeips\x18\x01 \x03(\t\"\x1b\n\x08nodeList\x12\x0f\n\x07nodeips\x18\x01 \x03(\t\"(\n\x16updateNodeListResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"!\n\x0fgeneralResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x14\n\x12generalPingRequest\"\"\n\x10newLeaderRequest\x12\x0e\n\x06nodeip\x18\x01 \x01(\t\"#\n\x11newLeaderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa9\x04\n\x11NodeCommunication\x12M\n\x0cupdateLeader\x12\x1c.stream1.updateLeaderRequest\x1a\x1d.stream1.updateLeaderResponse\"\x00\x12P\n\rproposeLeader\x12\x1d.stream1.proposeLeaderRequest\x1a\x1e.stream1.proposeLeaderResponse\"\x00\x12M\n\x08GetNodes\x12\x1e.stream1.GetListOfNodesRequest\x1a\x1f.stream1.GetListOfNodesResponse\"\x00\x12M\n\x15updateNodeMonitorList\x12\x11.stream1.nodeList\x1a\x1f.stream1.updateNodeListResponse\"\x00\x12\x46\n\x0b\x63heckLeader\x12\x1b.stream1.generalPingRequest\x1a\x18.stream1.generalResponse\"\x00\x12\x44\n\tsetLeader\x12\x19.stream1.newLeaderRequest\x1a\x1a.stream1.newLeaderResponse\"\x00\x12G\n\x0c\x63heckMonitor\x12\x1b.stream1.generalPingRequest\x1a\x18.stream1.generalResponse\"\x00\x42\x13\n\x0forg.node.protosP\x01\x62\x06proto3')



_PROPOSELEADERREQUEST = DESCRIPTOR.message_types_by_name['proposeLeaderRequest']
_PROPOSELEADERRESPONSE = DESCRIPTOR.message_types_by_name['proposeLeaderResponse']
_UPDATELEADERREQUEST = DESCRIPTOR.message_types_by_name['updateLeaderRequest']
_UPDATELEADERRESPONSE = DESCRIPTOR.message_types_by_name['updateLeaderResponse']
_GETLISTOFNODESREQUEST = DESCRIPTOR.message_types_by_name['GetListOfNodesRequest']
_GETLISTOFNODESRESPONSE = DESCRIPTOR.message_types_by_name['GetListOfNodesResponse']
_NODELIST = DESCRIPTOR.message_types_by_name['nodeList']
_UPDATENODELISTRESPONSE = DESCRIPTOR.message_types_by_name['updateNodeListResponse']
_GENERALRESPONSE = DESCRIPTOR.message_types_by_name['generalResponse']
_GENERALPINGREQUEST = DESCRIPTOR.message_types_by_name['generalPingRequest']
_NEWLEADERREQUEST = DESCRIPTOR.message_types_by_name['newLeaderRequest']
_NEWLEADERRESPONSE = DESCRIPTOR.message_types_by_name['newLeaderResponse']
proposeLeaderRequest = _reflection.GeneratedProtocolMessageType('proposeLeaderRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROPOSELEADERREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:stream1.proposeLeaderRequest)
  })
_sym_db.RegisterMessage(proposeLeaderRequest)

proposeLeaderResponse = _reflection.GeneratedProtocolMessageType('proposeLeaderResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROPOSELEADERRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:stream1.proposeLeaderResponse)
  })
_sym_db.RegisterMessage(proposeLeaderResponse)

updateLeaderRequest = _reflection.GeneratedProtocolMessageType('updateLeaderRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATELEADERREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:stream1.updateLeaderRequest)
  })
_sym_db.RegisterMessage(updateLeaderRequest)

updateLeaderResponse = _reflection.GeneratedProtocolMessageType('updateLeaderResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATELEADERRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:stream1.updateLeaderResponse)
  })
_sym_db.RegisterMessage(updateLeaderResponse)

GetListOfNodesRequest = _reflection.GeneratedProtocolMessageType('GetListOfNodesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETLISTOFNODESREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:stream1.GetListOfNodesRequest)
  })
_sym_db.RegisterMessage(GetListOfNodesRequest)

GetListOfNodesResponse = _reflection.GeneratedProtocolMessageType('GetListOfNodesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETLISTOFNODESRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:stream1.GetListOfNodesResponse)
  })
_sym_db.RegisterMessage(GetListOfNodesResponse)

nodeList = _reflection.GeneratedProtocolMessageType('nodeList', (_message.Message,), {
  'DESCRIPTOR' : _NODELIST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:stream1.nodeList)
  })
_sym_db.RegisterMessage(nodeList)

updateNodeListResponse = _reflection.GeneratedProtocolMessageType('updateNodeListResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATENODELISTRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:stream1.updateNodeListResponse)
  })
_sym_db.RegisterMessage(updateNodeListResponse)

generalResponse = _reflection.GeneratedProtocolMessageType('generalResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERALRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:stream1.generalResponse)
  })
_sym_db.RegisterMessage(generalResponse)

generalPingRequest = _reflection.GeneratedProtocolMessageType('generalPingRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERALPINGREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:stream1.generalPingRequest)
  })
_sym_db.RegisterMessage(generalPingRequest)

newLeaderRequest = _reflection.GeneratedProtocolMessageType('newLeaderRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEWLEADERREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:stream1.newLeaderRequest)
  })
_sym_db.RegisterMessage(newLeaderRequest)

newLeaderResponse = _reflection.GeneratedProtocolMessageType('newLeaderResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEWLEADERRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:stream1.newLeaderResponse)
  })
_sym_db.RegisterMessage(newLeaderResponse)

_NODECOMMUNICATION = DESCRIPTOR.services_by_name['NodeCommunication']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017org.node.protosP\001'
  _PROPOSELEADERREQUEST._serialized_start=23
  _PROPOSELEADERREQUEST._serialized_end=80
  _PROPOSELEADERRESPONSE._serialized_start=82
  _PROPOSELEADERRESPONSE._serialized_end=121
  _UPDATELEADERREQUEST._serialized_start=123
  _UPDATELEADERREQUEST._serialized_end=162
  _UPDATELEADERRESPONSE._serialized_start=164
  _UPDATELEADERRESPONSE._serialized_end=202
  _GETLISTOFNODESREQUEST._serialized_start=204
  _GETLISTOFNODESREQUEST._serialized_end=245
  _GETLISTOFNODESRESPONSE._serialized_start=247
  _GETLISTOFNODESRESPONSE._serialized_end=288
  _NODELIST._serialized_start=290
  _NODELIST._serialized_end=317
  _UPDATENODELISTRESPONSE._serialized_start=319
  _UPDATENODELISTRESPONSE._serialized_end=359
  _GENERALRESPONSE._serialized_start=361
  _GENERALRESPONSE._serialized_end=394
  _GENERALPINGREQUEST._serialized_start=396
  _GENERALPINGREQUEST._serialized_end=416
  _NEWLEADERREQUEST._serialized_start=418
  _NEWLEADERREQUEST._serialized_end=452
  _NEWLEADERRESPONSE._serialized_start=454
  _NEWLEADERRESPONSE._serialized_end=489
  _NODECOMMUNICATION._serialized_start=492
  _NODECOMMUNICATION._serialized_end=1045
# @@protoc_insertion_point(module_scope)
