# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11replication.proto\"\x17\n\x15GetListOfNodesRequest\")\n\x16GetListOfNodesResponse\x12\x0f\n\x07nodeips\x18\x01 \x03(\t\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\'\n\x15NodeDownUpdateRequest\x12\x0e\n\x06nodeip\x18\x01 \x01(\t2\x8f\x01\n\x0bReplication\x12;\n\x0eNodeDownUpdate\x12\x16.NodeDownUpdateRequest\x1a\x0f.StatusResponse\"\x00\x12\x43\n\x0eGetListOfNodes\x12\x16.GetListOfNodesRequest\x1a\x17.GetListOfNodesResponse\"\x00\x62\x06proto3')



_GETLISTOFNODESREQUEST = DESCRIPTOR.message_types_by_name['GetListOfNodesRequest']
_GETLISTOFNODESRESPONSE = DESCRIPTOR.message_types_by_name['GetListOfNodesResponse']
_STATUSRESPONSE = DESCRIPTOR.message_types_by_name['StatusResponse']
_NODEDOWNUPDATEREQUEST = DESCRIPTOR.message_types_by_name['NodeDownUpdateRequest']
GetListOfNodesRequest = _reflection.GeneratedProtocolMessageType('GetListOfNodesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETLISTOFNODESREQUEST,
  '__module__' : 'replication_pb2'
  # @@protoc_insertion_point(class_scope:GetListOfNodesRequest)
  })
_sym_db.RegisterMessage(GetListOfNodesRequest)

GetListOfNodesResponse = _reflection.GeneratedProtocolMessageType('GetListOfNodesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETLISTOFNODESRESPONSE,
  '__module__' : 'replication_pb2'
  # @@protoc_insertion_point(class_scope:GetListOfNodesResponse)
  })
_sym_db.RegisterMessage(GetListOfNodesResponse)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'replication_pb2'
  # @@protoc_insertion_point(class_scope:StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)

NodeDownUpdateRequest = _reflection.GeneratedProtocolMessageType('NodeDownUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _NODEDOWNUPDATEREQUEST,
  '__module__' : 'replication_pb2'
  # @@protoc_insertion_point(class_scope:NodeDownUpdateRequest)
  })
_sym_db.RegisterMessage(NodeDownUpdateRequest)

_REPLICATION = DESCRIPTOR.services_by_name['Replication']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETLISTOFNODESREQUEST._serialized_start=21
  _GETLISTOFNODESREQUEST._serialized_end=44
  _GETLISTOFNODESRESPONSE._serialized_start=46
  _GETLISTOFNODESRESPONSE._serialized_end=87
  _STATUSRESPONSE._serialized_start=89
  _STATUSRESPONSE._serialized_end=121
  _NODEDOWNUPDATEREQUEST._serialized_start=123
  _NODEDOWNUPDATEREQUEST._serialized_end=162
  _REPLICATION._serialized_start=165
  _REPLICATION._serialized_end=308
# @@protoc_insertion_point(module_scope)
